library;

import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:simple_baby_tracker/baby_profile.dart';
import 'package:simple_baby_tracker/helpers.dart';
import 'package:simple_baby_tracker/tracker_event.dart';

class PdfExportService {
  PdfExportService._();
  static final instance = PdfExportService._();

  // ─── Public API ───────────────────────────────────────────────────────────

  /// Generate and share/print the PDF using the system share sheet.
  Future<void> shareReport({
    required BabyProfile profile,
    required Map<String, List<TrackerEvent>> data,
    bool useKg = true,
    bool useCelsius = true,
  }) async {
    final bytes =
        await _buildPdf(profile: profile, data: data, useKg: useKg, useCelsius: useCelsius);
    await Printing.sharePdf(
      bytes: bytes,
      filename: 'baby_report_${profile.name.replaceAll(' ', '_')}.pdf',
    );
  }

  /// Generate the PDF and return its raw bytes (useful for saving to disk).
  Future<Uint8List> generateBytes({
    required BabyProfile profile,
    required Map<String, List<TrackerEvent>> data,
    bool useKg = true,
    bool useCelsius = true,
  }) =>
      _buildPdf(
          profile: profile, data: data, useKg: useKg, useCelsius: useCelsius);

  // ─── Builder ──────────────────────────────────────────────────────────────

  Future<Uint8List> _buildPdf({
    required BabyProfile profile,
    required Map<String, List<TrackerEvent>> data,
    required bool useKg,
    required bool useCelsius,
  }) async {
    final doc = pw.Document(
      title: '${profile.name} — Baby Tracker Report',
      author: 'Baby Tracker',
    );

    // Sort days newest-first for the report
    final sortedKeys = data.keys.toList()..sort((a, b) => b.compareTo(a));

    // Build summary stats
    int totalFeeds = 0, totalDiapers = 0, totalSleepMin = 0, totalMilk = 0;
    for (final events in data.values) {
      for (final e in events) {
        if (e.type == 'feeding') {
          totalFeeds++;
          totalMilk +=
              (e.data['amountMl'] as num?)?.toInt() ?? 0;
        }
        if (e.type == 'diaper') totalDiapers++;
        if (e.type == 'sleep') {
          totalSleepMin +=
              (e.data['durationMin'] as num?)?.toInt() ?? 0;
        }
      }
    }

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        header: (ctx) => _buildHeader(ctx, profile),
        footer: (ctx) => _buildFooter(ctx),
        build: (ctx) => [
          // Summary card
          _summarySection(
            totalFeeds: totalFeeds,
            totalDiapers: totalDiapers,
            totalSleepMin: totalSleepMin,
            totalMilk: totalMilk,
            dayCount: data.length,
          ),
          pw.SizedBox(height: 16),

          // Day-by-day entries
          ...sortedKeys.expand((key) {
            final events = data[key] ?? [];
            if (events.isEmpty) return <pw.Widget>[];
            return [
              _dayHeader(key),
              ...(List<TrackerEvent>.from(events)
                    ..sort((a, b) => a.time.compareTo(b.time)))
                  .map((e) => _eventRow(e, useKg, useCelsius)),
              pw.SizedBox(height: 8),
            ];
          }),
        ],
      ),
    );

    return doc.save();
  }

  // ─── Header / footer ──────────────────────────────────────────────────────

  pw.Widget _buildHeader(pw.Context ctx, BabyProfile profile) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              '${profile.name} — Baby Tracker Report',
              style: pw.TextStyle(
                  fontSize: 16, fontWeight: pw.FontWeight.bold),
            ),
            pw.Text(
              fullDate(DateTime.now()),
              style: const pw.TextStyle(
                  fontSize: 10, color: PdfColors.grey600),
            ),
          ],
        ),
        if (profile.birthDate != null)
          pw.Text(
            'Date of birth: ${fullDate(profile.birthDate!)}  ·  ${profile.ageString}',
            style: const pw.TextStyle(
                fontSize: 10, color: PdfColors.grey600),
          ),
        pw.Divider(color: PdfColors.grey400),
        pw.SizedBox(height: 4),
      ],
    );
  }

  pw.Widget _buildFooter(pw.Context ctx) {
    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          'Generated by Baby Tracker',
          style: const pw.TextStyle(
              fontSize: 9, color: PdfColors.grey500),
        ),
        pw.Text(
          'Page ${ctx.pageNumber} of ${ctx.pagesCount}',
          style: const pw.TextStyle(
              fontSize: 9, color: PdfColors.grey500),
        ),
      ],
    );
  }

  // ─── Summary section ──────────────────────────────────────────────────────

  pw.Widget _summarySection({
    required int totalFeeds,
    required int totalDiapers,
    required int totalSleepMin,
    required int totalMilk,
    required int dayCount,
  }) {
    final sleepH = totalSleepMin ~/ 60;
    final sleepM = totalSleepMin % 60;
    final sleepStr =
        sleepH > 0 ? '${sleepH}h ${sleepM}m' : '${sleepM}m';

    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(6),
        border: pw.Border.all(color: PdfColors.blue200),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Summary — $dayCount day${dayCount == 1 ? '' : 's'} of data',
            style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold, fontSize: 12),
          ),
          pw.SizedBox(height: 8),
          pw.Row(children: [
            _statChip('Feeds', '$totalFeeds'),
            pw.SizedBox(width: 16),
            _statChip('Diapers', '$totalDiapers'),
            pw.SizedBox(width: 16),
            _statChip('Sleep', sleepStr),
            pw.SizedBox(width: 16),
            _statChip('Milk', '${totalMilk}ml'),
          ]),
        ],
      ),
    );
  }

  pw.Widget _statChip(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(label,
            style: const pw.TextStyle(
                fontSize: 9, color: PdfColors.grey600)),
        pw.Text(value,
            style: pw.TextStyle(
                fontSize: 13, fontWeight: pw.FontWeight.bold)),
      ],
    );
  }

  // ─── Day header ───────────────────────────────────────────────────────────

  pw.Widget _dayHeader(String dateKey) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 4, bottom: 4),
      padding: const pw.EdgeInsets.symmetric(
          horizontal: 8, vertical: 4),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey200,
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(
        fullDate(dateFromKey(dateKey)),
        style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold, fontSize: 11),
      ),
    );
  }

  // ─── Event row ────────────────────────────────────────────────────────────

  pw.Widget _eventRow(
      TrackerEvent e, bool useKg, bool useCelsius) {
    final time = formatTime(e.time);
    final (icon, title, detail) = _eventContent(e, useKg, useCelsius);

    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(
          vertical: 2, horizontal: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 42,
            child: pw.Text(time,
                style: const pw.TextStyle(
                    fontSize: 9, color: PdfColors.grey600)),
          ),
          pw.SizedBox(
            width: 14,
            child: pw.Text(icon,
                style: const pw.TextStyle(fontSize: 10)),
          ),
          pw.Expanded(
            child: pw.RichText(
              text: pw.TextSpan(children: [
                pw.TextSpan(
                  text: '$title  ',
                  style: pw.TextStyle(
                      fontSize: 10,
                      fontWeight: pw.FontWeight.bold),
                ),
                pw.TextSpan(
                  text: detail,
                  style: const pw.TextStyle(
                      fontSize: 10, color: PdfColors.grey700),
                ),
              ]),
            ),
          ),
        ],
      ),
    );
  }

  (String icon, String title, String detail) _eventContent(
      TrackerEvent e, bool useKg, bool useCelsius) {
    switch (e.type) {
      case 'diaper':
        final pee = e.data['pee'] == true;
        final poo = e.data['poo'] == true;
        final rash = e.data['rash'] == true;
        final contents = [
          if (pee) 'pee',
          if (poo) 'poo',
        ].join(' + ');
        final rashStr = rash ? '  🔴 Rash' : '';
        final size = e.data['size'] as String?;
        final brand = e.data['brand'] as String?;
        final extra = [
          if (size != null) 'Size $size',
          ?brand,
        ].join('  ·  ');
        return ('👶', 'Diaper${contents.isNotEmpty ? ' ($contents)' : ''}$rashStr',
            extra);

      case 'feeding':
        final isBottle = (e.data['isBottle'] as bool?) ?? true;
        if (isBottle) {
          final ml = e.data['amountMl'] ?? 0;
          final method = e.data['method'] == 'formula'
              ? 'Formula'
              : 'Breast milk';
          final brand = e.data['formulaBrand'] as String?;
          return ('🍼', 'Bottle ($method)',
              '$ml ml${brand != null ? '  ·  $brand' : ''}');
        }
        final dur = e.data['durationMin'] ?? 0;
        return ('🤱', 'Breastfeeding', '$dur min');

      case 'sleep':
        final min = (e.data['durationMin'] as num?)?.toInt() ?? 0;
        final h = min ~/ 60;
        final rem = min % 60;
        final dur = h > 0 ? '${h}h ${rem}m' : '${rem}m';
        final notes = e.data['notes'] as String?;
        return ('😴', 'Sleep ($dur)',
            notes ?? '');

      case 'temperature':
        final c = (e.data['valueCelsius'] as num?)?.toDouble() ?? 0;
        final sev = tempSeverity(c);
        final dot = switch (sev) {
          'fever' => '🔴',
          'elevated' => '🟠',
          'low' => '🔵',
          _ => '🟢',
        };
        return ('🌡️', 'Temperature $dot',
            formatTemp(c, useCelsius: useCelsius));

      case 'weight':
        final kg = (e.data['valueKg'] as num?)?.toDouble() ?? 0;
        return ('⚖️', 'Weight', formatWeight(kg, useKg: useKg));

      case 'tummy_time':
        final min = (e.data['durationMin'] as num?)?.toInt() ?? 0;
        return ('🏋️', 'Tummy time', '$min min');

      case 'medication':
        final name = e.data['name'] as String? ?? '';
        final dose = e.data['dose'];
        final unit = e.data['unit'] ?? '';
        return ('💊', 'Medication: $name',
            dose != null ? '$dose $unit' : '');

      case 'doctor_visit':
        final reason = e.data['reason'] as String? ?? '';
        final doctor = e.data['doctorName'] as String?;
        final weightKg =
            (e.data['weightKg'] as num?)?.toDouble();
        final heightCm =
            (e.data['heightCm'] as num?)?.toDouble();
        final headCm =
            (e.data['headCm'] as num?)?.toDouble();
        final measurements = [
          if (weightKg != null)
            formatWeight(weightKg, useKg: useKg),
          if (heightCm != null) '${heightCm}cm height',
          if (headCm != null) '${headCm}cm head',
        ].join('  ·  ');
        return ('🏥', 'Doctor visit — $reason',
            [?doctor, measurements]
                .where((s) => s.isNotEmpty)
                .join('  ·  '));

      case 'pumping':
        final total = ((e.data['leftMl'] as num? ?? 0) +
                (e.data['rightMl'] as num? ?? 0))
            .toInt();
        final stored = e.data['stored'] == true ? '  (stored)' : '';
        return ('🥛', 'Pumping', '$total ml$stored');

      case 'bath':
        final type = e.data['bathType'] as String? ?? 'tub';
        return ('🛁', 'Bath (${type[0].toUpperCase()}${type.substring(1)})', '');

      case 'note':
        final title = e.data['title'] as String?;
        final text = e.data['text'] as String? ?? '';
        final preview =
            text.length > 80 ? '${text.substring(0, 80)}…' : text;
        return ('📝', title ?? 'Note', preview);

      default:
        return ('•', e.type, '');
    }
  }
}